<h1>Help - Configuration</h1> 

<h3>My Profile</h3>
<p>This view shows information for the current system user. From here you can</p>
<ul class="std">
    <li>Modify your password (if your user-type supports doing so)</li>
    <li>Modify your notification E-Mail address</li>
    <li>Modify your display name (info)</li>
    <li>View your assigned group</li>
</ul>

<h2>Administration Panels</h2>

<h3>Settings</h3>
<p>This view displays Application Statistics and allows for the modification of system settings. Each setting has a small description of how it is used in the system.</p>

<h3>Maintenance</h3>
<p>This view allows for &quot;basic&quot; database maintenance and resets. A warning is always displayed of this view to remind you that the actions are permanent. Each action is described. The optimize feature is used for updating and cleaning MySQL indexes and usually is unnecessary for normal opperation.</p>

<h3>Groups</h3>
<p>This view displays defined user groups. You are able to add new user groups and edit existing groups. A user group is a way to separate users and tickets and give more permissions to a Moderator user.</p>

<h3>Users</h3>
<p>This view displays system user. You are able to add new users and edit any user that is not the current user.</p>