<?php
if ($this->id === 'new') {
    $type = 'Add';
} else {
    $type = 'Edit';
    $this->headScript()->appendFile($this->baseUrl('js/jquery.base64.js'));
    $this->headScript()->appendFile($this->baseUrl('js/jquery.grid.js'));
}
?>
<?php $this->headTitle("Configuration - Groups ($type)"); ?>
<?php echo $this->render('config/toolbar.phtml'); ?>
<h1><?php echo $type; ?> Group</h1>
<?php echo $this->form; ?>
<?php if ($this->id !== 'new'): ?>
<div class="clr"></div>
<h2>Group Users</h2>
<div id="userGrid">
    <?php echo $this->render('config/grid/users.phtml'); ?>
</div>
<script type="text/javascript">
$('#userGrid').grid('<?php echo $this->url(array('ajax' => true)); ?>', { useAjax:true });
</script>
<?php endif; ?>