<?php
$onReady = <<<EOD
$(function(){
    $('#report_head').hover(function(){
        $('ul', this).toggle();
    });
});
EOD;
$this->headScript()->appendScript($onReady);
?>
<?php $this->headScript()->appendFile($this->baseUrl('js/jquery.grid.js')); ?>
<?php $this->headTitle($this->reportName); ?>
<?php echo $this->render('messages.phtml'); ?>
<div id="report_head">
    <h1><?php echo $this->escape($this->reportName); ?></h1>
    <?php if (!empty($this->reports)): ?>
    <ul>
    <?php foreach($this->reports as $i => $report): ?>
        <li><a href="<?php echo $this->url(array('id' => $i + 1), 'report', true); ?>">{<?php echo $i + 1; ?>} <?php echo $this->escape($report['name']); ?></a></li>
    <?php endforeach; ?>
    </ul>
    <?php endif; ?>
</div>
<div class="clear"></div>
<div id="ticketGrid">
    <?php echo $this->render('report/grid.phtml'); ?>
</div>
<script type="text/javascript">
$('#ticketGrid').grid('<?php echo $this->url(array('ajax' => true)); ?>', { useAjax:true });
</script>
