<?php if (!empty($this->metanav)): ?>
<div class="two_col right">
<div id="metanav" class="nav">
	<div class="nav_wrapper">
        <ul>
        	<?php foreach ($this->metanav as $i => $nav): ?>
        	<li<?php echo $this->classDecorator(null, false, $i, count($this->metanav)); ?>>
        		<a href="<?php echo $this->url(array(
        		    'controller' => $nav['controller'],
        		    'action' => $nav['action']
        		), 'default', true); ?>"><?php echo $nav['label']; ?></a>
        	</li>
        	<?php endforeach; ?>
        </ul>
    </div>
</div>
</div>
<div class="clear"></div>
<?php endif; ?>