<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
<!--
    Membership and regular participation in the UNL Web Developer Network
    is required to use the UNL templates. Visit the WDN site at 
    http://wdn.unl.edu/. Click the WDN Registry link to log in and
    register your unl.edu site.
    All UNL template code is the property of the UNL Web Developer Network.
    The code seen in a source code view is not, and may not be used as, a 
    template. You may not use this code, a reverse-engineered version of 
    this code, or its associated visual presentation in whole or in part to
    create a derivative work.
    This message may not be removed from any pages based on the UNL site template.
    
    $Id: php.document.dwt.php 536 2009-07-23 15:47:30Z bbieber2 $
-->
  <link rel="stylesheet" type="text/css" media="screen" href="/wdn/templates_3.0/css/all.css" />
  <link rel="stylesheet" type="text/css" media="print" href="/wdn/templates_3.0/css/print.css" />
  <script type="text/javascript" src="/wdn/templates_3.0/scripts/all.js"></script>
  <?php echo file_get_contents($this->serverUrl('/wdn/templates_3.0/includes/browserspecifics.html')); ?>
  <?php echo file_get_contents($this->serverUrl('/wdn/templates_3.0/includes/metanfavico.html')); ?>
  <?php
  $this->headTitle($this->escape($this->siteTitle), 'PREPEND');
  $this->headTitle($this->escape('UNL'), 'PREPEND');
  echo $this->headTitle()->setSeparator(' | ');
  $pageTitle = $this->headTitle()->getContainer()->getArrayCopy();
  $pageTitle = end($pageTitle);
  ?>
  <?php
  $this->headLink()->prependStylesheet($this->designUrl('css', 'ieLt8.css'), 'screen', 'lt IE 8');
  $this->headLink()->prependStylesheet($this->designUrl('css', 'ie8.css'), 'screen', 'IE 8');
  $this->headLink()->prependStylesheet($this->designUrl('css', 'global.css'));
  echo $this->headLink(); 
  ?>
  <?php echo $this->headStyle(); ?>
  <?php echo $this->headScript(); ?>
</head>
<body class="document">
<p class="skipnav"> <a class="skipnav" href="#maincontent">Skip Navigation</a> </p>
<div id="wdn_wrapper">
    <div id="header"> <a href="http://www.unl.edu/" title="UNL website"><img src="/wdn/templates_3.0/images/logo.png" alt="UNL graphic identifier" id="logo" /></a>
        <h1>University of Nebraska&ndash;Lincoln</h1>
    </div>
  <div id="wdn_navigation_bar">
        <div id="breadcrumbs">
            <!-- WDN: see glossary item 'breadcrumbs' -->
            <!-- TemplateBeginEditable name="breadcrumbs" -->
			<ul>
				<li class="first"><a href="http://www.unl.edu/">UNL</a></li>
				<li><a href="http://ucomm.unl.edu/">UComm</a></li>
				<li><a href="<?php echo $this->baseUrl(); ?>">Support Request System</a></li>
				<li><?php echo $pageTitle; ?></li>
			</ul>
			 <!-- TemplateEndEditable --></div>
        <div id="wdn_navigation_wrapper">
            <div id="navigation"><!-- TemplateBeginEditable name="navlinks" -->
				<ul>
	 				<li><a href="<?php echo $this->baseUrl(); ?>">Home</a></li>
				</ul>
				<!-- TemplateEndEditable -->
				<div id="navigation-close" style="display: none;"></div>
				<div id="navigation-expand-collapse"><span>roll over for full navigation</span></div>
			</div>
        </div>
    </div>
    
    
    
  <div id="wdn_content_wrapper">
        <div id="titlegraphic">
            <h1><a href="<?php echo $this->baseUrl(); ?>"><?php echo $this->escape($this->siteBanner); ?></a></h1>
            <!-- TemplateEndEditable --></div>
        <div id="pagetitle"> </div>
        <div id="maincontent">
        	<div class="four_col">
        	<?php echo $this->render('metanav.phtml'); ?>
            <?php echo $this->layout()->content ?>
            </div>
            <div class="clear"></div>
            <?php echo file_get_contents($this->serverUrl('/wdn/templates_3.0/includes/noscript.html')); ?>
            <!--THIS IS THE END OF THE MAIN CONTENT AREA.-->
        </div>
        <div id="footer">
            <div id="footer_floater"></div>
            <div id="wdn_copyright"><!-- TemplateBeginEditable name="footercontent" -->
                <?php echo file_get_contents('http://www.unl.edu/ucomm/sharedcode/footer.html'); ?>
                <!-- TemplateEndEditable -->
                <?php echo file_get_contents($this->serverUrl('/wdn/templates_3.0/includes/wdn.html')); ?>
                | <a href="http://validator.unl.edu/check/referer">W3C</a> | <a href="http://jigsaw.w3.org/css-validator/check/referer?profile=css3">CSS</a> <a href="http://www.unl.edu/" title="UNL Home" id="wdn_unl_wordmark"><img src="/wdn/templates_3.0/css/footer/images/wordmark.png" alt="UNL's wordmark" /></a> </div>
        </div>
    </div>
    <div id="wdn_wrapper_footer"> </div>
</div>
</body>
</html>