<table class="actions">
    <tbody>
        <tr>
            <td class="pager">
                <?php echo $this->paginator; ?>
            </td>
            <td class="filter-actions a-right">
                <input class="reset" type="button" value="Reset Filter" />
                <input class="filter" type="button" value="Search" />
            </td>
        </tr>
    </tbody>
</table>
<table class="data full-width">
    <thead>
        <tr class="headings">
            <th>Name</th>
            <th>Shortname</th>
            <th class="no-link">Assigned Users</th>
            <th class="no-link">Action</th>
        </tr>
        <tr class="filters">
            <th>
                <div>
                    <input type="text" name="name" value="<?php echo $this->escape(isset($this->filters['name']) ? $this->filters['name'] : ''); ?>" />
                </div>
            </th>
            <th>
                <div>
                    <input type="text" name="shortname" value="<?php echo $this->escape(isset($this->filters['shortname']) ? $this->filters['shortname'] : ''); ?>" />
                </div>
            </th>
            <th class="no-link">&nbsp;</th>
            <th class="no-link">&nbsp;</th>
        </tr>
    </thead>
    <tbody>
    <?php if ($this->paginator->count()): ?>
    <?php $i = 0; ?>
    <?php foreach ($this->paginator as $id => $group): ?>
        <?php $_url = $this->url(array(
            'controller' => 'config',
            'action' => 'groups',
            'id' => $group['ugroup_id']
        ), 'default', true); ?>
        <tr<?php echo ($i % 2 == 0 ? '' : ' class="alt"'); ?> title="<?php echo $_url; ?>">
            <td><?php echo $this->escape($group['name']); ?></td>
            <td><?php echo $this->escape($group['shortname']); ?></td>
            <td><?php echo $group['count']; ?></td>
            <td><a href="<?php echo $_url; ?>">Edit</a></td>
        </tr>
    <?php $i++; ?>
    <?php endforeach; ?>
    <?php else: ?>
        <tr>
            <td colspan="4">[None]</td>
        </tr>
    <?php endif; ?>
    </tbody>
</table>
