<?php if (!empty($this->metanav)): ?> 
<div id="metanav" class="nav"> 
        <ul> 
        	<?php foreach ($this->metanav as $i => $nav): ?>
        	<li<?php echo $this->classDecorator(null, empty($nav['active']) ? false : $nav['active'], $i, count($this->metanav)); ?>>
        		<a href="<?php echo $this->url(array(
        		    'controller' => $nav['controller'],
        		    'action' => $nav['action']
        		), 'default', true); ?>"><?php echo $nav['label']; ?></a>
        	</li>
        	<?php endforeach; ?>
        </ul> 
</div> 
<?php endif; ?>