<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <link href="<?php echo $this->designUrl('images', 'Developper-16x16.ico'); ?>" rel="shortcut icon"/>
  <?php
  $this->headTitle($this->escape($this->siteTitle), 'PREPEND');
  echo $this->headTitle()->setSeparator(' | ')
  ?>
  <?php
  $this->headLink()->prependStylesheet($this->designUrl('css', 'ieLt8.css'), 'screen', 'lt IE 8');
  $this->headLink()->prependStylesheet($this->designUrl('css', 'ie8.css'), 'screen', 'IE 8');
  $this->headLink()->prependStylesheet($this->designUrl('css', 'global.css'));
  echo $this->headLink();
  ?>
  <?php echo $this->headStyle(); ?>
  <?php
  $this->headScript()->prependFile($this->baseUrl('js/jquery-1.4.4.min.js'));
  echo $this->headScript();
  ?>
</head>
<body>
<div id="container">
  <div id="header">
  	<a href="<?php echo $this->baseUrl(); ?>">
		<img style="float:left; padding-right: 10px;" src="<?php echo $this->designUrl('images', 'Developper-128x128.png'); ?>" alt="logo" />
    	<span class="title"><?php echo $this->escape($this->siteBanner); ?></span>
        <span class="subtitle">The No-Flair Issue Tracker</span>
    </a>
  </div>
  <?php echo $this->render('metanav.phtml'); ?>
  <?php echo $this->render('mainnav.phtml'); ?>
  <div id="maincontent">
    <?php echo $this->layout()->content ?>
  </div>
  <div id="footer">
    <p>&copy; 2011 Kevin Abel | Lincoln, NE 68504 | <a href="mailto:comments@example.com">comments?</a></p>
    <p>Validated with <a href="http://validator.w3.org/check/referer">W3C</a> | <a href="http://jigsaw.w3.org/css-validator/check/referer?profile=css3">CSS</a></p>
  </div>
</div>
</body>
</html>