<?php $this->headTitle('Configuration - Groups'); ?>
<?php $this->headScript()->appendFile($this->baseUrl('js/jquery.base64.js')); ?>
<?php $this->headScript()->appendFile($this->baseUrl('js/jquery.grid.js')); ?>
<?php echo $this->render('config/toolbar.phtml'); ?>
<?php echo $this->render('messages.phtml'); ?>
<h1>User Groups</h1> 
<p class="a-right"><a class="add-group" href="<?php echo $this->url(array(
    'id' => 'new'
));?>">Add Group</a></p>
<div id="groupGrid">
    <?php echo $this->render('config/grid/groups.phtml'); ?>
</div>
<script type="text/javascript">
$('#groupGrid').grid('<?php echo $this->url(); ?>', { useAjax:true });
</script>
